using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class SoccerAI : MonoBehaviour
{
    // stay near goal
    // find ball coming towards goal
    // block it
    BasicMovement bm;
    public float dashChance;
    float prevTheta;

    public GameObject closestBall;

    public float centerWeight = 1;
    public float sigma;
    public Vector3 goalTransform;
    int i =0;
       float theta;
    void Awake(){
        bm = transform.GetComponent<BasicMovement>();
        centerWeight = .1f;
        sigma = .15f;
        dashChance = .006f;
    }
    void Start()
    {
        
    }

    //Generated by Box-Muller Transform
    float GenerateNormalNoise(float sigma, float  mu)
    {
        float num1 = Random.value;
        float num2 = Random.value;

       
        float z = Mathf.Sqrt(-2 * Mathf.Log(num1)) * Mathf.Cos(2*Mathf.PI * num2);
        return z * sigma + mu;
    }   

    // Update is called once per frame
    void Update()
    {
        
    }

    void FixedUpdate()
    {
     
        //Update goal position
        if(Random.value < dashChance){
            bm.Dash();
            Debug.Log("AI Dash");
        }
        bm.Moving();
      //  bm.movementDirection = (goalWeight * goalVector + (ballWeight / minDistance) * toBall).normalized;
       // Debug.Log((goalWeight * goalVector + (ballWeight / minDistance) * toBall).normalized);
       if(i % 5 == 0){
        theta = GenerateNormalNoise(sigma,prevTheta);
        prevTheta = theta;
       }
       Vector2 rNV = new Vector2(Mathf.Cos(theta), Mathf.Sin(theta));
       Vector2 centerBias = centerWeight * (new Vector2(transform.position.x,transform.position.z));
       
        
       
        bm.movementDirection = (rNV - centerBias).normalized;

        
    }
}
